"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import { store } from './store'
import { Provider } from 'react-redux'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-300" >
        <div className='bg-zinc-800 text-slate-300'>
          <nav className='w-10/12 mx-auto flex justify-evenly items-center py-2 font-bold text-xl'>
            <Link href="/">Home</Link>
            <Link href="/ListUsers">List & Add Users</Link>
          </nav>
        </div>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  )
}
